name: task_effeciency
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  calendar_date_picker2: ^1.1.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  intl: ^0.20.1
  lottie: ^3.2.0
  riverpod: ^2.6.1
  shared_preferences: ^2.3.4
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff" # Opsional untuk Android (warna latar belakang ikon adaptif)
  adaptive_icon_foreground: "assets/logo.png" # Opsional untuk ikon adaptif

flutter:
  uses-material-design: true
  assets:
    - assets/
